Lexicon_LMS/Models/Document.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Lexicon_LMS.Models
{
    public class Document
    {
        public int DocumentId { get; set; }
        public string ApplicationUserId { get; set; }
        public int? GroupId { get; set; }
        public int? CourseId { get; set; }
        public int? ActivityId { get; set; }
        public string Title { get; set; }
        public string FileName { get; set; }
        public string Description { get; set; }
        public DateTime TimeStamp { get; set; }

        public virtual Group Group { get; set; }
        public virtual Course Course { get; set; }
        public virtual Activity Activity { get; set; }
        [ForeignKey("ApplicationUserId")]
        public virtual ApplicationUser ApplicationUser { get; set; }
    }
}

Lexicon_LMS/Controllers/DocumentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lexicon_LMS.Models;
using System.IO;

namespace Lexicon_LMS
{
    public class DocumentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Documents
        public ActionResult Index(int? gid, int? cid, int? aid)
        {
            var documents = db.Documents.Include(d => d.Activity).Include(d => d.ApplicationUser).Include(d => d.Course).Include(d => d.Group);
            var docs = documents.Where(d => d.CourseId == cid && d.GroupId == gid && d.ActivityId == aid);
            return View(docs.ToList());
        }

        // GET: Documents/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Document document = db.Documents.Find(id);
            if (document == null)
            {
                return HttpNotFound();
            }
            return View(document);
        }

        // GET: Documents/Create
        public ActionResult Create(int? gId, int? cId, int? aId)
        {
            //ViewBag.AId = new SelectList(db.Activities, "ActivityId", "Type");
            //ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "FirstName");
            //ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Name");
            //ViewBag.GroupId = new SelectList(db.Groups, "GroupId", "Name");
            Document document = new Document();
            document.ActivityId = aId;
            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "FirstName");
            document.CourseId = cId;
            document.GroupId = gId;
            return View(document);
        }

        // POST: Documents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DocumentId,ApplicationUserId,GroupId,CourseId,ActivityId,Title,FileName,Description,TimeStamp")] Document document, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
 
                if (upload != null && upload.ContentLength > 0)
                {
                //    var _document = new Document
                //    {
                //        //upload.
                //    };
                    //string str = Path.Combine(Server.MapPath("~/LMS_Documents"),System.IO.Path.GetFileName(upload.FileName));
                    document.FileName = System.IO.Path.GetFileName(upload.FileName);
                    upload.SaveAs(Path.Combine(Server.MapPath("~/LMS_Documents"), upload.FileName));
                    //course.Documents = new List<Document>();
                    //course.Documents.Add(document);
                }
                db.Documents.Add(document);
                db.SaveChanges();
                return RedirectToAction("Index", new { gId = document.GroupId, cId = document.CourseId, aId = document.ActivityId });
            }

            ViewBag.ActivityId = new SelectList(db.Activities, "ActivityId", "Type", document.ActivityId);
            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "FirstName", document.ApplicationUserId);
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Name", document.CourseId);
            ViewBag.GroupId = new SelectList(db.Groups, "GroupId", "Name", document.GroupId);
            return View(document);
        }

        // GET: Documents/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Document document = db.Documents.Find(id);
            if (document == null)
            {
                return HttpNotFound();
            }
            ViewBag.ActivityId = new SelectList(db.Activities, "ActivityId", "Type", document.ActivityId);
            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "FirstName", document.ApplicationUserId);
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Name", document.CourseId);
            ViewBag.GroupId = new SelectList(db.Groups, "GroupId", "Name", document.GroupId);
            return View(document);
        }

        // POST: Documents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DocumentId,ApplicationUserId,GroupId,CourseId,ActivityId,Title,FileName,Description,TimeStamp")] Document document)
        {
            if (ModelState.IsValid)
            {
                db.Entry(document).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { gId = document.GroupId, cId = document.CourseId, aId = document.ActivityId });
            }
            ViewBag.ActivityId = new SelectList(db.Activities, "ActivityId", "Type", document.ActivityId);
            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "FirstName", document.ApplicationUserId);
            ViewBag.CourseId = new SelectList(db.Courses, "CourseId", "Name", document.CourseId);
            ViewBag.GroupId = new SelectList(db.Groups, "GroupId", "Name", document.GroupId);
            return View(document);
        }

        // GET: Documents/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Document document = db.Documents.Find(id);
            if (document == null)
            {
                return HttpNotFound();
            }
            return View(document);
        }

        // POST: Documents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Document document = db.Documents.Find(id);
            db.Documents.Remove(document);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Lexicon_LMS/Views/Documents/Create.cshtml
@model Lexicon_LMS.Models.Document

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@*@using (Html.BeginForm())*@ 
@using (Html.BeginForm("Create", "Documents", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Document</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ApplicationUserId, "ApplicationUserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ApplicationUserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ApplicationUserId, "", new { @class = "text-danger" })
            </div>
        </div>

        @*@Html.HiddenFor(m => m.GroupId)
        @Html.HiddenFor(m => m.CourseId)
        @Html.HiddenFor(m => m.ActivityId)*@

 @*       @Model.GroupId = ViewBag.GId;*@
      @*  @Model.CourseId = ViewBag.CId;*@
    @*    @Model.ActivityId = ViewBag.GId;*@


        @*<div class="form-group">
            @Html.LabelFor(model => model.GroupId, "GroupId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GroupId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GroupId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.GroupId, "GroupId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.GroupId, new { @Value = @Model.GroupId, @readonly = "true" })
                @Html.ValidationMessageFor(model => model.GroupId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CourseId, "CourseId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.CourseId, new { @Value = @Model.CourseId, @readonly = "true" })
                @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ActivityId, "ActivityId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ActivityId, new { @Value = @Model.ActivityId, @readonly = "true" })
                @Html.ValidationMessageFor(model => model.ActivityId, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div cla@*ss="form-group">
            @Html.LabelFor(model => model.ActivityId, "ActivityId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ActivityId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ActivityId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FileName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Doc" name="upload" />
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.FileName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileName, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TimeStamp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TimeStamp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TimeStamp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Lexicon_LMS/Views/Documents/Delete.cshtml
@model Lexicon_LMS.Models.Document

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Document</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Activity.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Activity.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Group.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Group.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeStamp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeStamp)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Lexicon_LMS/Views/Documents/Details.cshtml
@model Lexicon_LMS.Models.Document

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Document</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Activity.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Activity.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Group.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Group.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeStamp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeStamp)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.DocumentId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Lexicon_LMS/Views/Documents/Index.cshtml
@model IEnumerable<Lexicon_LMS.Models.Document>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Lägg till dokument", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Activity.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApplicationUser.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Course.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Group.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FileName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TimeStamp)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Activity.Type)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ApplicationUser.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Course.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Group.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FileName)
            @*@Html.ActionLink(Html.DisplayFor(modelItem => item.FileName), "Details", new { id = item.DocumentId })*@
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TimeStamp)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.DocumentId }) |
            @Html.ActionLink("Details", "Details", new { id=item.DocumentId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.DocumentId })
        </td>
    </tr>
}

</table>