Lexicon_LMS/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lexicon_LMS.Models;


namespace Lexicon_LMS
{
    [Authorize(Roles = "Teacher")]
    public class GroupsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Groups
        public ActionResult Index()
        {
            string userName = User.Identity.Name;
            var activeUser = db.Users.Where(u => u.UserName == User.Identity.Name.ToString()).ToList().FirstOrDefault();
            //string activeUser = User.Identity.ToString();
            string fullName = FindTeacherName(userName); //anropar metod som utifrån mailadress(userName) returnerar för- och efternamn på lärare.
            //var firstName = (from u in db.Users
            //                 where u.UserName == userName
            //                 select u.FirstName).FirstOrDefault();

            //var lastName = (from u in db.Users
            //               where u.UserName == userName
            //               select u.LastName).FirstOrDefault();

            ////string fullName = firstName + " " + lastName;
            //string fullName = firstName + " " + lastName;




            //var _firstName = db.Users.Where(u => u.UserName == userName);
            //var _lastName = db.Users.Where(u => u.UserName == userName);

            //var iD = db.Users.Where(i => i.Email == userName);
            //var iD = (from p in db.Users where p.Email == userName select p.Id).FirstOrDefault();
            //var user = db.Users.Where(u => u.Id == iD).FirstOrDefault().Roles.FirstOrDefault().;

            // User.IsInRole("Teacher");
            //User.IsInRole("Student");

            //var roleId = from r in db. where r. == iD select r.Id;
            //var rId = roleId;

            //int userId = db.
            //if (User.Identity.Name == "oscar.jakobsson@lexicon.se")

            ViewBag.TeacherName = fullName;
            ViewBag.TeacherId = User.Identity.Name;
            //return View();
            return View(db.Groups.Where(g => g.TeacherId == activeUser.Id).OrderBy(d => d.StartDate));
        }


        // GET: All Groups
        public ActionResult ListAllGroups()
        {
            string userName = User.Identity.Name;
            string fullName = FindTeacherName(userName); //anropar metod som utifrån mailadress(userName) returnerar för- och efternamn på lärare.
            // var activeUser = db.Users.Where(u => u.UserName == User.Identity.Name.ToString()).ToList().FirstOrDefault();
            var activeUserId = db.Users.Where(u => u.UserName == User.Identity.Name.ToString()).ToList().FirstOrDefault();

            //var activeUserId = (from u in db.Users
            //                    where u.UserName == userName
            //                    select u.Id).FirstOrDefault();



            //var firstName = (from u in db.Users
            //                 where u.UserName == userName
            //                 select u.FirstName).FirstOrDefault();

            //var lastName = (from u in db.Users
            //                where u.UserName == userName
            //                select u.LastName).FirstOrDefault();

            // fullName = firstName + " " + lastName;

            //ViewBag.TeacherName = fullName;
            ViewBag.TeacherId = activeUserId;

            //ViewData["AllUsers"] = db.Users;
            //ViewBag.Teacher = User.Identity.Name;


            return View(db.Groups.OrderBy(d => d.StartDate));

        }



        // GET: All Groups
        public ActionResult AdministrateGroups()
        {
            string userName = User.Identity.Name;
            string fullName = FindTeacherName(userName); //anropar metod som utifrån mailadress(userName) returnerar för- och efternamn på lärare.
            var activeUserId = db.Users.Where(u => u.UserName == User.Identity.Name.ToString()).ToList().FirstOrDefault();

            ViewBag.TeacherId = activeUserId;

            //ViewData["AllUsers"] = db.Users;
            //ViewBag.Teacher = User.Identity.Name;
            return View(db.Groups.OrderBy(d => d.StartDate));

        }

        // GET: All Groups
        //public ActionResult AdministrateGroupsEdit()
        //{
        //    string userName = User.Identity.Name;
        //    string fullName = FindTeacherName(userName); //anropar metod som utifrån mailadress(userName) returnerar för- och efternamn på lärare.
        //    var activeUserId = db.Users.Where(u => u.UserName == User.Identity.Name.ToString()).ToList().FirstOrDefault();

        //    ViewBag.TeacherId = activeUserId;

        //    //ViewData["AllUsers"] = db.Users;
        //    //ViewBag.Teacher = User.Identity.Name;
        //    return View(db.Groups.OrderBy(d => d.StartDate));
        //}

        // GET: Groups/AdministrateGroupsEdit/5
        public ActionResult AdministrateGroupsEdit(int? id)
        {
            string userName = User.Identity.Name;
            string fullName = FindTeacherName(userName);
            ViewBag.TeacherName = fullName;
            var defaultGroup = db.Groups.Where(u => u.GroupId == id);
                        
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            ViewBag.TeacherId = new SelectList(db.Users.Where(u => u.GroupId == null), "Id", "FullName", group.TeacherId);
            return View(group);
        }


        // POST: Groups/AdministrateGroupsEdit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult AdministrateGroupsEdit([Bind(Include = "GroupId,TeacherId,Teacher,Name,Description,StartDate,EndDate")] Group group)
        public ActionResult AdministrateGroupsEdit([Bind(Include = "GroupId,TeacherId,Name,Description,StartDate,EndDate")] Group group)
        {
            if (ModelState.IsValid)
            {
                db.Entry(group).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("../Groups/AdministrateGroups");
            }
            ViewBag.TeacherId = new SelectList(db.Users.Where(u => u.GroupId == null), "Id", "FullName", group.TeacherId);
            return View(group);
        }


        // GET: Groups/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            ViewBag.GroupName = group.Name;

            return View(group);
        }




         //GET: Groups/Create
        public ActionResult Create()
        {
            //ViewBag.All = db.Groups.Select(h => new SelectListItem
            //{
            //    Value = h.TeacherId.ToString(),
            //});
            //return View();
           // ViewBag.GroupId = new SelectList(db.Groups, "GroupId", "Name");

            ViewBag.TeacherId = new SelectList(db.Users.Where(u => u.GroupId == null), "Id", "FullName");
            return View();
        }



        // POST: Groups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GroupId,Name,TeacherId,Description,StartDate,EndDate")] Group group)
        {
            if (ModelState.IsValid)
            {
                db.Groups.Add(group);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TeacherId = new SelectList(db.Users.Where(u => u.GroupId == null), "Id", "FullName", group.TeacherId);

            return View(group);
        }


        // GET: Groups/Edit/5
        public ActionResult Edit(int? id)
        {
            string userName = User.Identity.Name;
            string fullName = FindTeacherName(userName);
            ViewBag.TeacherName = fullName;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            ViewBag.TeacherId = group.TeacherId;

            return View(group);
        }



        // POST: Groups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "GroupId,TeacherId, Teacher, Name,Description,StartDate,EndDate")] Group group)
        {
            if (ModelState.IsValid)
            {
                db.Entry(group).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(group);
        }


        // GET: Groups/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {

Lexicon_LMS/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lexicon_LMS.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;

namespace Lexicon_LMS.Controllers
{
    public class UsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Users
        public ActionResult Index(int? groupId)
        {
            var ActiveUser = db.Users.Where(u => u.UserName == User.Identity.Name.ToString()).ToList().FirstOrDefault();

            if (groupId != null)
            {
                if (User.IsInRole("Teacher"))
                {
                    var users = db.Users.Where(u => u.GroupId == groupId);
                    ViewBag.GroupName = users.FirstOrDefault().Group.Name;
                    ViewBag.Group_Id = groupId;
                    return View(users.ToList());
                }
                else
                {
                    var ActiveGroup = db.Groups.Where(g => g.GroupId == ActiveUser.GroupId);
                    ViewBag.GroupName = ActiveGroup.First().Name;
                    ViewBag.Group_Id = ActiveGroup.First().GroupId;
                    var users = db.Users.Where(u => u.GroupId == ActiveUser.GroupId);
                    return View(users.ToList());
                }
            }
            else
            {
                if (ActiveUser.GroupId != null)
                {
                    return RedirectToAction("index");
                }
                else
                {
                    if (User.IsInRole("Teacher"))
                    {
                        ViewBag.Group_Id = groupId;
                        var users = db.Users.Where(u => u.GroupId == groupId);
                        return View(users.ToList());
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
            }

        }

        // GET: Users/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            ViewBag.Group_Id = applicationUser.GroupId;
            return View(applicationUser);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,GroupId,FirstName,LastName,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(applicationUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(applicationUser);
        }


        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateTeacher([Bind(Include = "Id,GroupId,FirstName,LastName,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(applicationUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(applicationUser);
        }


        // GET: Users/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            ViewBag.Group_Id = applicationUser.GroupId;
            return View(applicationUser);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Id,GroupId,FirstName,LastName,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] ApplicationUser applicationUser)
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,Email")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                var userStore = new UserStore<ApplicationUser>(db);
                var userManager = new UserManager<ApplicationUser>(userStore);

                var user = db.Users.Where(u => u.Id == applicationUser.Id).FirstOrDefault();
                var groupId = user.GroupId;
                user.FirstName = applicationUser.FirstName;
                user.LastName = applicationUser.LastName;
                user.Email = applicationUser.Email;
                user.UserName = user.Email;


                userManager.Update(user);
                db.SaveChanges();

                return RedirectToAction("Index", new { GroupId = groupId });
            }
            return View(applicationUser);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            ViewBag.Group_Id = applicationUser.GroupId;
            return View(applicationUser);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ApplicationUser applicationUser = db.Users.Find(id);
            var groupId = applicationUser.GroupId;
            db.Users.Remove(applicationUser);
            db.SaveChanges();
            return RedirectToAction("Index", new { GroupId = groupId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Lexicon_LMS/Views/Groups/AdministrateGroups.cshtml
@model IEnumerable<Lexicon_LMS.Models.Group>

@{
    ViewBag.Title = "AdministrateGroups";
}

<h4>Administrera grupper/lärare / @Html.ActionLink("Mina grupper", "Index")</h4>

@*<p>
        @Html.ActionLink("Åter till mina grupper", "Index")
    </p>
    <p>
        @Html.ActionLink("Skapa ny grupp", "Create")
    </p>
    <p>
        @Html.ActionLink("Skapa ny lärare", "../Account/CreateTeacher")
    </p>
    <p>
        @Html.ActionLink("Lista alla lärare", "Index", "Users")
    </p>*@

<td>
    @*@Html.ActionLink("Åter till mina grupper", "Index") |*@
    @Html.ActionLink("Skapa ny grupp", "Create", null, new { @class = "btn btn-default btn-m" })
    @Html.ActionLink("Registrera ny lärare", "../Account/CreateTeacher", null, new { @class = "btn btn-default btn-m" })
    @Html.ActionLink("Lista alla lärare", "Index", "Users", null, new { @class = "btn btn-default btn-m" })
    <br />
</td>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TeacherId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @*@Html.ActionLink(item.Name, "Index", "Courses", new { id = item.GroupId }, null)*@
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Teacher.FirstName)
                @Html.DisplayFor(modelItem => item.Teacher.LastName)
                @*@Html.DisplayFor(modelItem => item.Teacher.LastName)*@
            </td>
            <td>
                @{
                    string str = (string)item.Description;
                    if (str.Count() > 7)
                    {
                        str = str.Substring(0, 7);
                    }
                    //str = str.Substring(0, 7); << vad händer om det bara finns 7 stycken tecken??
                }
                @str...
                @*@Html.DisplayFor(modelItem => item.Description)*@
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>

            <td>
                @Html.ActionLink("Detaljer", "Details", new { id = item.GroupId }, new { @class = "btn btn-default btn-xs" })
                @Html.ActionLink("Ändra", "AdministrateGroupsEdit", new { id = item.GroupId }, new { @class = "btn btn-default btn-xs" })
                @Html.ActionLink("Ta Bort", "Delete", new { id = item.GroupId }, new { @class = "btn btn-default btn-xs" })
            </td>

        </tr>
    }

</table>

Lexicon_LMS/Views/Groups/AdministrateGroupsEdit.cshtml
@model Lexicon_LMS.Models.Group
@{
    ViewBag.Title = "AdministrateGroupsEdit";
}

<h2>Ändra grupp</h2>

@*<h2>Editera @ViewBag.TeacherName:s grupp</h2>*@


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.GroupId)
        @*@Html.HiddenFor(model => model.TeacherId)*@


        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>


        @*<div class="form-group">
            @Html.LabelFor(model => model.TeacherId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Teacher, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Teacher, "", new { @class = "text-danger" })
            </div>
        </div>*@


        @*@Html.HiddenFor(model => model.TeacherId)*@


        <div class="form-group">
            @Html.LabelFor(model => model.TeacherId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TeacherId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TeacherId, "", new { @class = "text-danger" })
            </div>
        </div>


        @*<div class="form-group">
            @Html.LabelFor(model => model.TeacherId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TeacherId, new { htmlAttributes = new { @class = "form-control" } })

                @Html.DropDownList("TeacherId", null, htmlAttributes: new { @class = "form-control" })
                @Html.DropDownList("GroupId", null, htmlAttributes: new { _Enabled = "false" })

                @Html.ValidationMessageFor(model => model.TeacherId, "", new { @class = "text-danger" })
            </div>
        </div>*@




        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spara" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @*@Html.ActionLink("Tillbaka till Administrera", "../Groups/AdministrateGroups")*@
    @Html.ActionLink("Tillbaka till Administrera", "../Groups/AdministrateGroups", null, new { @class = "btn btn-default btn-m" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Lexicon_LMS/Views/Groups/Create.cshtml
@model Lexicon_LMS.Models.Group

@{
    ViewBag.Title = "Create";
}

<h2>Skapa ny grupp</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @*<h4>Group</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Teacher, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Teacher, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Teacher, "", new { @class = "text-danger" })
            </div>
        </div>*@


        <div class="form-group">
            @Html.LabelFor(model => model.TeacherId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TeacherId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TeacherId, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Skapa grupp" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @*@Html.ActionLink("Åter till grupplistan", "Index")*@
    @Html.ActionLink("Åter till grupplistan", "Index", null, new { @class = "btn btn-default btn-m" })
    @*new { @class = "btn btn-default btn-m" }*@
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Lexicon_LMS/Views/Groups/Index.cshtml
@model IEnumerable<Lexicon_LMS.Models.Group>

@{
    ViewBag.Title = "Index";
    int? gId = null;
    int? cId = null;
    int? aId = null;
}

<h4>
    / @Html.ActionLink("Samtliga grupper på Lexicon", "ListAllGroups", "Groups") / Mina grupper
</h4>


<td>
    @*@Html.ActionLink("Lista samtliga grupper på Lexicon", "ListAllGroups")  *@
    @*@Html.ActionLink("Skapa ny grupp", "Create")*@
    @*@Html.ActionLink("Skapa ny grupp", "Create", null, new { @class = "btn btn-default btn-m" }, new { id = User.Identity })*@
    @Html.ActionLink("Skapa ny grupp", "Create", null, new { @class = "btn btn-default btn-m" })
</td>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Teacher)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th></th>
    </tr>


@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.Name, "Index", "Courses", new { id = item.GroupId }, null)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>*@
        <td>
           
            @{
                string str = (string)item.Description;
                if(str.Count() > 7)
                {
                    str = str.Substring(0, 7); 
                }
                //str = str.Substring(0, 7); << vad händer om det bara finns 7 stycken tecken??
            }
            @str...
            @*@Html.DisplayFor(modelItem => item.Description)*@

        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.ActionLink("Detaljer", "Details", new { id = item.GroupId }, new { @class = "btn btn-default btn-xs" })
            @Html.ActionLink("Ändra", "Edit", new { id = item.GroupId }, new { @class = "btn btn-default btn-xs" })
            @Html.ActionLink("Ta bort", "Delete", new { id = item.GroupId }, new { @class = "btn btn-default btn-xs" })
            @Html.ActionLink("Lägg till dokument", "Create", "Documents", new { gId = item.GroupId, cId, aId}, new { @class = "btn btn-default btn-xs" })
            @Html.ActionLink("Visa dokument", "Index", "Documents", new { gId = item.GroupId, cId, aId }, new { @class = "btn btn-default btn-xs" })
        </td>
    </tr>
}

</table>