Lexicon_LMS/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lexicon_LMS.Models;

namespace Lexicon_LMS
{
    public class CoursesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Courses
        //public ActionResult Index()
        //{
        //    var ActiveUser = db.Users.Where(u => u.UserName == User.Identity.Name.ToString()).ToList().FirstOrDefault();

        //    ViewBag.Message = "Du är inloggad " + ActiveUser.FirstName + " " + ActiveUser.LastName + " du deltager i: " + db.Groups.First().Name;
        //    ViewBag.Message2 = db.Groups.First().Name;
        //    var courses = db.Courses.Where(c => c.GroupId == ActiveUser.GroupId);
        //    //            var activities = db.Activities.Where(a => a.CourseId == AKTUELLT_KURS_ID).ToList();

        //    //var courses = db.Courses.Include(c => c.Group).Where(c => c.GroupId == db.Users.Where(u => u.GroupId.ToString() == c.GroupId()).ToList().FirstOrDefault().FirstName;
        //    return View(courses.ToList());
        //}

        // GET: Courses/5
        public ActionResult Index(int? id)
        {
            var ActiveUser = db.Users.Where(u => u.UserName == User.Identity.Name.ToString()).ToList().FirstOrDefault();

            if (id != null)
            {
                if (User.IsInRole("Teacher"))
                {
                    var courses = db.Courses.Where(c => c.GroupId == id).OrderBy(a => a.StartDate);
                    ViewBag.GroupName = db.Groups.Where(g => g.GroupId == id).FirstOrDefault().Name;
                    ViewBag.Group_Id = id;
                    return View(courses.ToList());
                }
                else
                {
                    var courses = db.Courses.Where(c => c.GroupId == id).OrderBy(a => a.StartDate);
                    ViewBag.GroupName = db.Groups.Where(g => g.GroupId == id).FirstOrDefault().Name;
                    ViewBag.Group_Id = id;
                    return View(courses.ToList());
                }
            }
            else
            {
                if (ActiveUser.GroupId != null)
                {
                    var ActiveGroup = db.Groups.Where(g => g.GroupId == ActiveUser.GroupId);
                    ViewBag.Message = "Du är inloggad " + ActiveUser.FullName + " du deltager i: " + ActiveGroup.First().Name;
                    ViewBag.GroupName = ActiveGroup.First().Name;
                    ViewBag.Group_Id = ActiveGroup.First().GroupId;
                    var courses = db.Courses.Where(c => c.GroupId == ActiveUser.GroupId).OrderBy(a => a.StartDate);
                    return View(courses.ToList());
                }
                else
                {
                    if (User.IsInRole("Teacher"))
                    {
                        return RedirectToAction("Index", "Groups");
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
            }

        }

        // GET: Courses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // GET: Courses/Create
        public ActionResult Create()
        {
            ViewBag.GroupId = new SelectList(db.Groups, "GroupId", "Name");
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CourseId,GroupId,Name,Teacher,Description,StartDate,EndDate")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Courses.Add(course);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.GroupId = new SelectList(db.Groups, "GroupId", "Name", course.GroupId);
            return View(course);
        }

        // GET: Courses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            ViewBag.GroupId = new SelectList(db.Groups, "GroupId", "Name", course.GroupId);
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CourseId,GroupId,Name,Teacher,Description,StartDate,EndDate")] Course course)
        {
            if (ModelState.IsValid)
            {
                db.Entry(course).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GroupId = new SelectList(db.Groups, "GroupId", "Name", course.GroupId);
            return View(course);
        }

        // GET: Courses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = db.Courses.Find(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Course course = db.Courses.Find(id);
            db.Courses.Remove(course);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Lexicon_LMS/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lexicon_LMS.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;

namespace Lexicon_LMS.Controllers
{
    public class UsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Users
        public ActionResult Index(int? groupId)
        {
            var ActiveUser = db.Users.Where(u => u.UserName == User.Identity.Name.ToString()).ToList().FirstOrDefault();

            if (groupId != null)
            {
                if (User.IsInRole("Teacher"))
                {
                    var users = db.Users.Where(u => u.GroupId == groupId);
                    ViewBag.GroupName = users.FirstOrDefault().Group.Name;
                    ViewBag.Group_Id = groupId;
                    return View(users.ToList());
                }
                else
                {
                    var ActiveGroup = db.Groups.Where(g => g.GroupId == ActiveUser.GroupId);
                    ViewBag.GroupName = ActiveGroup.First().Name;
                    ViewBag.Group_Id = ActiveGroup.First().GroupId;
                    var users = db.Users.Where(u => u.GroupId == ActiveUser.GroupId);
                    return View(users.ToList());
                }
            }
            else
            {
                if (ActiveUser.GroupId != null)
                {
                    return RedirectToAction("index");
                }
                else
                {
                    if (User.IsInRole("Teacher"))
                    {
                        ViewBag.Group_Id = groupId;
                        var users = db.Users.Where(u => u.GroupId == groupId);
                        return View(users.ToList());
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
            }

        }

        // GET: Users/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            ViewBag.Group_Id = applicationUser.GroupId;
            return View(applicationUser);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,GroupId,FirstName,LastName,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(applicationUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(applicationUser);
        }


        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateTeacher([Bind(Include = "Id,GroupId,FirstName,LastName,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(applicationUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(applicationUser);
        }


        // GET: Users/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            ViewBag.Group_Id = applicationUser.GroupId;
            return View(applicationUser);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Id,GroupId,FirstName,LastName,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] ApplicationUser applicationUser)
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,Email")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                var userStore = new UserStore<ApplicationUser>(db);
                var userManager = new UserManager<ApplicationUser>(userStore);

                var user = db.Users.Where(u => u.Id == applicationUser.Id).FirstOrDefault();
                var groupId = user.GroupId;
                user.FirstName = applicationUser.FirstName;
                user.LastName = applicationUser.LastName;
                user.Email = applicationUser.Email;
                user.UserName = user.Email;


                userManager.Update(user);
                db.SaveChanges();

                return RedirectToAction("Index", new { GroupId = groupId });
            }
            return View(applicationUser);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = db.Users.Find(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            ViewBag.Group_Id = applicationUser.GroupId;
            return View(applicationUser);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ApplicationUser applicationUser = db.Users.Find(id);
            var groupId = applicationUser.GroupId;
            db.Users.Remove(applicationUser);
            db.SaveChanges();
            return RedirectToAction("Index", new { GroupId = groupId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Lexicon_LMS/Views/Courses/CourseOfGroup.cshtml
@model IEnumerable<Lexicon_LMS.Models.Course>

@{
    ViewBag.Title = "CourseOfGroup";
}

<h2>CourseOfGroup</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Group.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Teacher)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Group.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Teacher)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CourseId }) |
            @Html.ActionLink("Details", "Details", new { id=item.CourseId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CourseId })
        </td>
    </tr>
}

</table>

Lexicon_LMS/Views/Courses/Create.cshtml
@model Lexicon_LMS.Models.Course

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@*@using (Html.BeginForm())*@ 
@using (Html.BeginForm("Create", "Courses", null, FormMethod.Post, new {enctype = "multipart/form-data"}))

{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.GroupId, "GroupId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GroupId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GroupId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Teacher, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Teacher, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Teacher, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Documents, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Doc" name="upload" />
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tillbaka till kurslistan", "Index", new { id = ViewBag.Group_Id }, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Lexicon_LMS/Views/Courses/Delete.cshtml
@model Lexicon_LMS.Models.Course

@{
    ViewBag.Title = "Delete";
}

<h2>Ta bort kurs @Model.Name och underliggande aktiviteter</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Group.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Group.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Teacher)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Teacher)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Ta bort" class="btn btn-default" /> |
            @Html.ActionLink("Tillbaka till kurslistan", "Index", new { id = Model.GroupId }, null)
        </div>
    }
</div>

Lexicon_LMS/Views/Courses/Details.cshtml
@model Lexicon_LMS.Models.Course

@{
    ViewBag.Title = "Details";
}

<h2>Detaljer för kursen</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Group.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Group.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Teacher)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Teacher)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Ändra", "Edit", new { id = Model.CourseId }) |
    @Html.ActionLink("Tillbaka till kurslistan", "Index", new { id = Model.GroupId }, null)
</p>

Lexicon_LMS/Views/Courses/Edit.cshtml
@model Lexicon_LMS.Models.Course

@{
    ViewBag.Title = "Edit";
}

<h2>Ändra kursen</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CourseId)

        <div class="form-group">
            @Html.LabelFor(model => model.GroupId, "GroupId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GroupId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GroupId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Teacher, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Teacher, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Teacher, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tillbaka till kurslistan", "Index", new { id = Model.GroupId }, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Lexicon_LMS/Views/Courses/Index.cshtml
@model IEnumerable<Lexicon_LMS.Models.Course>

@{
    ViewBag.Title = "Index";
    string GroupName = "ERROR";
    int? gId = null;
    int? aId = null;
    int? cId = null;

    if (ViewBag.GroupName != null)
    {
        GroupName = ViewBag.GroupName;
    }
}


@if (User.IsInRole("Teacher"))
{
    <h4>/ @Html.ActionLink("Lista samtliga grupper på Lexicon", "ListAllGroups", "Groups") / @Html.ActionLink("Mina grupper", "Index", "Groups") / @ViewBag.GroupName / Kurser
    </h4>

    <p>
        @Html.ActionLink("Skapa ny kurs", "Create")
    </p>

    @*<p>
        @Html.ActionLink("Skapa document", "Create", "Documents", new { gId, cId = 1, aId }, null)
    </p>*@
}
else
{
    <h4>
       / @ViewBag.GroupName / Kurser
    </h4>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Teacher)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Documents.FileName)
        </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.Name, "Index", "Activities", new { id = item.CourseId }, null)
                @*@Html.DisplayFor(modelItem => item.Name)*@
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Teacher)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            @if (User.IsInRole("Teacher"))
            {
                <td>
                    @Html.ActionLink("Detaljer", "Details", new { id = item.CourseId }, new { @class = "btn btn-default btn-xs" })
                    @Html.ActionLink("Ändra", "Edit", new { id = item.CourseId }, new { @class = "btn btn-default btn-xs" })
                    @Html.ActionLink("Ta bort", "Delete", new { id = item.CourseId }, new { @class = "btn btn-default btn-xs" })
                    @Html.ActionLink("Lägg till dokument", "Create", "Documents", new { gId, cId = item.CourseId, aId }, new { @class = "btn btn-default btn-xs" })
                    @Html.ActionLink("Visa dokument", "Index", "Documents", new { gId, cId = item.CourseId, aId }, new { @class = "btn btn-default btn-xs" })
                </td>
            }
            else
            {
                <td>
                    @Html.ActionLink("Detaljer", "Details", new { id = item.CourseId }, new { @class = "btn btn-default btn-xs" })
                    @Html.ActionLink("Lägg till dokument", "Create", "Documents", new { gId, cId = item.CourseId, aId }, new { @class = "btn btn-default btn-xs" })
                    @Html.ActionLink("Visa dokument", "Index", "Documents", new { gId, cId = item.CourseId, aId }, new { @class = "btn btn-default btn-xs" })
                </td>

            }
        </tr>
    }

</table>
@if (User.IsInRole("Teacher"))
{
    <p>@Html.ActionLink("Se samtliga elever", "Index", "Users", new { groupId = @ViewBag.Group_Id }, new { @class = "btn btn-default btn-m" })</p>
}
else
{
    <p>@Html.ActionLink("Se samtliga elever", "Index", "Users", new { groupId = @ViewBag.Group_Id }, new { @class = "btn btn-default btn-m" })</p>
}